### ISSUE TITLE
Packet counter starts at -1 ?

### ISSUE THREAD

**Issue by zanco** [RoelKroes/TBTracker#20]
Hi, downloaded lastest, changed settings.h and noticed the string counter started at -1 

![image](https://user-images.githubusercontent.com/4477734/218844494-cc7f3044-f343-4688-8df2-6c87afaecdcd.png)

**Comment by RoelKroes** [comment]
This is actually a feature :-)

You see this because the software gets the packetcounter from eeprom.  if it does not find a packetcounter present in eeprom, it will init to  -1. 

If you don't want this behaviour you can uncomment the line "#define RESET_TRANS_COUNTERS" and run the software once. It will init the counter in eeprom to "0".  Then upload again with the line commented again.
